version: "3"
services:
  payment_service:
    build: ./
    container_name: payment_service_prod
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
    networks:
      - network
    command: npm run start
networks:
  network:
    name: api_network
    external: true
